<?php

namespace Database\Seeders;

// use Illuminate\Database\Console\Seeds\WithoutModelEvents; --: laravel comment

use App\Models\Course;
use App\Models\User;
use Illuminate\Database\Seeder;

class DatabaseSeeder extends Seeder
{
    /**
     * Seed the application's database.
     */
    public function run(): void
    {
        // autogenerated laravel seed
        User::factory(3)->create();

        // \App\Models\User::factory()->create([
        //     'name' => 'Test User',
        //     'email' => 'test@example.com',
        // ]);

        // example for import from seeder, you must be add all seeders here
        // $this->call([
        //     CourseSeeder::class
        // ]);

        //example for laraver recommendation
        //Missing import model and can delete CourseSeeder seeder because it is
        //unnecessary
        Course::factory(50)->create();
    }
}
